language: java
jdk:
  - openjdk8

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r freelec-bulletinBoard *
  - mkdir -p deploy
  - mv freelec-bulletinBoard.zip deploy/freelec-bulletinBoard.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-bulletin-board-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true #master branch가 아닐 경우 추가

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-bulletin-board-build
    key: freelec-bulletinBoard.zip
    bundle_type: zip
    application: freelec-bulletin-board
    deployment_group: freelec-bulletin-board-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jooss287@gmail.com